apiVersion: v1
kind: Pod
metadata:
  name: emptydir
  # namespace: roboshop
  labels:
    name: roboshop
    env: dev
sepc:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMount:
    - mountPath: /var/log/nginx
      name: nginx-log
  - name: almalinux
    image: almalinux:8
    command: ["sleep","1000"] 
    volumeMount:
    - mountPath: /sample/nginx
      name: nginx-log
      readOnly: true
  volumes:
  - name: nginx
    emptyDir:
      sizeLimit: 100Mi
