apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment
  labels:
    names: roboshop
    env: dev
    language: yaml
    purpose: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      names: roboshop
      env: dev
      language: yaml
      purpose: deployment
  template:
    metadata:
      labels:
        names: roboshop
        env: dev
        language: yaml
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:trixie-perl
        resources:
          requests:
            cpu: "150mm"
            memory: "256Mi"
          limits:
            cpu: "200mm"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip
spec:
  type: ClusterIP
  selector:
    names: roboshop
    env: dev
    language: yaml
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: headless
spec:
  clusterIP: None
  selector:
    names: roboshop
    env: dev
    language: yaml
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80