apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: statefulset
  labels:
    names: roboshop
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      names: roboshop
      env: dev
  template:
    metadata:
      labels:
        names: roboshop
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:trixie-perl
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: nginx-html
    nodeSelector:
      topology.kubernetes.io/zone: us-east-1c
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: ebs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: statefulset
spec:
  ClusterIP: none
  selector:
    names: roboshop
    env: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: statefulset
spec:
  type: ClusterIP
  selector:
    names: roboshop
    env: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80